let a=10;
let b=20;
let c=32;
let d=19;
let e;
let w="true";
let r='sita';
let j=10;
console.log(a+b);
console.log(d+e);
console.log(w+r);
console.log(d+w);
console.log(a*b);
console.log(a*w);
console.log(a+w);
console.log(a<b);
console.log(d<a);
console.log(d>=a);
console.log(a==j);
console.log(a===j)